### ISSUE TITLE
关于cookie失效，无法持续登录的问题

### ISSUE THREAD

**Issue by haoranpb** [tsengkasing/Tongji4m3Notice-TGBot#2]
我在用python爬4m3时也遇到过同样的问题
在尝试使用抓包工具分析后，发现4m3使用了SAML验证，搜索了下，没太看懂。但是我认为可以简单地理解成，4m3开启SAML验证后，cookie是会**过期**的
最后用selenium+chromedriver模拟人工登录，避开了这个问题
我的项目[WatchDog 定时抓取4m3信息并发送邮箱](https://github.com/ludanxer/WatchDog)

**Comment by tsengkasing** [comment]
才注意到这个issue，不知道为啥三个月前没收到邮件提醒 orz
按你说的属实，所以的确还是每次发请求走一遍登录流程了orz
